### ISSUE TITLE
Having trouble running script on entries from New Zealand

### ISSUE THREAD

**Issue by sumant-28** [quantumgardener/dayone-to-obsidian#2]
There is an exception on line 46. Something about pytz not behaving properly with timezone gmt+1200. I'm trying to debug and fix it myself but I am not good with Python so I may never figure out the solution

**Comment by quantumgardener** [comment]
Sorry to hear you’re having difficulty. It’s something I got working for my case and I didn’t have to dig too deep. 

All I can suggest is splitting out that line 46 into its component parts and testing each. 

From localDate = createDate.astimezone(pytz.timezone(entry['timeZone'])) to

x = pytz.timezone(entry['timeZone'])
localDate = createDate.astimezone(x)

This will confirm where the problem lies. Also check value of createDate from the previous line. print(createDate) will be your friend. 

That may help.

**Comment by sumant-28** [comment]
Hello there thanks for the quick response. I figured out that in the JSON file I'm importing almost all timezone tags are Pacific/\Auckland but one rogue posting had the aforementioned gmt+1200. After editing it the code executes.

**Comment by quantumgardener** [comment]
Glad you got it sorted.
